#!/usr/bin/env python3

import sys
from utils import handle_flags, loadDB, scan_diretory

def main():
    dirname = handle_flags()
    db = loadDB()
    if dirname == -1:
        print("GUI has not been implemented yet")
        sys.exit(2)
    else:
        scan_diretory(dirname, db)
        sys.exit(0)

if __name__ == '__main__':
    main()
