#!/usr/bin/env python3

import sys
from gui import init_gui
from __init__ import __version__
from utils import handle_flags, loadDB, scan_diretory

def main():
    dirname = handle_flags()
    db = loadDB()
    if dirname == -2:
        print("akari version {}".format(__version__))
        sys.exit(0)
    if dirname == -1:
        print("GUI has not been implemented yet")
        init_gui()
    else:
        scan_diretory(dirname, db)
        sys.exit(0)

if __name__ == '__main__':
    main()
